# Site

title: Quick start with Python
authors:
  - Philippe Marchand

# Slides

slide_sorter:
  - objective
  - lists
  - types
  - dict
  - flow
  - def
  - packages
  - conclude

baseurl: '/basic-Python-lesson'
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
