# Build

markdown: kramdown
collections:
  slides:
    output: false
  views:
    output: true
    permalink: /:name/
  archive:
    output: true
    permalink: /:year/:month/:day/:title:output_ext

# Asset URLs

imageurl: /assets/images/
styleurl: /assets/css/
