# Site

title: Data Tools in Python
handouts: worksheet.py
tag: v0.0
lesson: 9
instructor: Kelly Hondula
authors:
  - Philippe Marchand
  - Ian Carroll

# Slides

slide_sorter:
  - objective
  - assignment # key difference is "=" for assignment
  - flow # key difference from R is that white space matters
  - def
  - types
  - list
  - dict
  - comps
  - packages
#  - numpy
  - pandas
#  - matplotlib
  - sqlalchemy
  - conclude

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/1.1/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
