# Site

title: Quick start with Python
worksheet: worksheet.py
tag: v0.0
lesson: 0
instructor: Philippe Marchand
authors:
  - Philippe Marchand

# Slides

slide_sorter:
  - objective
  - types
  - lists
  - dict
  - flow
  - def
  - packages
  - conclude

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.1
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0

# Jekyll

markdown: kramdown
collections:
  - slides
